apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quay-public-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quay-public-component
    app.kubernetes.io/part-of: e2e-quayio
  name: quay-public-component
  namespace: appstudio-e2e-test
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: quay-public-component
    weight: 100
status: {}
